name: Verify RC Package

on:
  pull_request:
    types: [labeled]

permissions:
  contents: read
  packages: read

jobs:
  get-version:
    if: github.event.label.name == 'verify' && github.event.pull_request.state == 'open'
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
      - id: version
        run: echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT

  integration-test:
    needs: get-version
    if: github.event.label.name == 'verify' && github.event.pull_request.state == 'open'
    uses: agim89/shared-workflows/.github/workflows/consumer-verify.yml@main
    with:
      version: ${{ needs.get-version.outputs.version }}-dev-
      remote: conan-rc
    secrets: inherit
